### PR TITLE
Pass return values (promises) from Client

### PR DESCRIPTION
**Pull request by maciejmrozinski**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
FYI the official react cache interface doesn't support this

**Comment by maciejmrozinski** [comment]
Do You think we can add this to `Cache Interface`? Seems reasonable

**Comment by WyriHaximus** [comment]
Seems reasonable to me as well, could you raise an issue on react/cache?

**Comment by maciejmrozinski** [comment]
[Done](https://github.com/reactphp/cache/issues/15)

**Pull request merged**
